<center>
    <img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/Logos/organization_logo/organization_logo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>


#### Add your code below following the instructions given in the course


# My Jupyter Notebook on IBM Watson Studio

**Taleb Beder Sabag**
<br>
I'm currently studying Physical Engineering, I want to do a PHD in Astronomy.

*I'm interested in Data Science since it is an area that a lot of companies are interested and I believe it is useful in every way, you can analyze things like why public transport is being delayed daily to even predict what is the most probable type of Star a galaxy will have.*

### The code will generate an empty matrix with a size defined by M and N 

In [3]:
import numpy as np
def null_matrix(M,N):
    m_i=np.zeros( (M,N) )
    print(m_i)
null_matrix(4,4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Cell 6 content**
- Table 
- Image 
- Hyperlink
<br>

|Variable 1| Variable 2| Sum|
|:-:|:-:|:-:|
|1 | 2 | 3|
|10 | 20 | 30|

<br>

[Hyperlink](https://www.ibm.com/docs/en/db2-event-store/2.0.0?topic=notebooks-markdown-jupyter-cheatsheet)

<br>

![Sun.jpg](Sun.jpg)

